/**
 * axis_logo - the AXIS Communications lockup shown at the bottom of the
 * display preview, as a base64 PNG.
 *
 * GENERATED FILE - do not edit. Produced from axis-logo.png in the
 * project root by embed-logo.sh, which build.command runs on every
 * build. To change the artwork, replace that PNG and rebuild.
 *
 * Embedded rather than linked because a strict Content-Security-Policy
 * on the proxied path blocks external assets - the same reason the
 * C8310 photo lives in panel_image.h.
 *
 * While AXIS_LOGO_B64 is empty, webui.c falls back to a hand-drawn SVG
 * reconstruction of the lockup.
 */
#ifndef AXIS_LOGO_H
#define AXIS_LOGO_H

#define AXIS_LOGO_B64 \
    "iVBORw0KGgoAAAANSUhEUgAAAu4AAAEWCAYAAAA5NBIjAAAMn0lEQVR4nO3dvY7kRBcGYE+rbwKRECIihAhY4PJZFgkhIkRIgriN" \
    "JRgJNep1j9122eetep7wE7vrn7J9vnPeqXl5//tfHycAAKC0y9kHAAAAvO06TdP0/ddfvJx9IAAAwDwddwAACKBwBwCAAAp3AAAI" \
    "oHAHAIAACncAAAhwPfsAAAB69+H9L//93px3P3xnNz+eouMOAAABFO4AABBAVAYAoIHbeMzc/y42wxo67gAAEEDhDgAAAURlAABO" \
    "IjbDGjruAAAQQOEOAAABRGUAAHYyt5MM7EHHHQAAAijcAQAggKgMAMAGe8Vj7DDDW3TcAQAggMIdAAACKNwBACCAwh0AAAIo3AEA" \
    "IIBdZQAAVmr9i5bsMMOn6LgDAEAAhTsAAAS4mr0AALytdTxmyb8rNjO2y+T2AwBAeaIyAAAQQOEOAAABFO4AABBA4Q4AAAGuk59O" \
    "BQD4pLN2kpljh5mx6bgDAEAAhTsAAAS4nn0AAACVVIvHzBGbGY+OOwAABFC4AwBAAIU7AAAEULgDAEAAhTsAAASwqwwAMLyUnWTm" \
    "2GFmDDruAAAQQOEOAAABRGUAgCGlx2PmiM30S8cdAAACKNwBACCAqAwAh0iPJbSOHCy5PmIPMDYddwAACKBwBwCAAKIy4SqPnreM" \
    "dCuf1xLp4+zE6z93zSufS+I6qXw9U2y5hnN/NnEtnWW0NWyHmb7ouAMAQACFOwAABBCVCTTCmO92nDfC+VaQeJ2NfdtJXA+VLYm4" \
    "rN1V5va/F4dgCeskn447AAAEULgDAEAAURlowDiyHddzXyIx51oboXG/nuO60QsddwAACHDRugIAgPpEZUKMPOZL32Gmcmwm8Xqy" \
    "nft+riXvtC07zPDKNXms8reJeaIyAAAQ4DL5/1gAAFCeqAwMJnF8bIy7XeJ9555nAcYmKgMAAAEU7gAAEEBUpjCj7Xvpuyj4Kf7l" \
    "XJ/tEp+REWzZMcY9fcz1eY5vUw4ddwAACKBwBwCAAKIyxRjzLZcemzmS6zMO95rRWPP7EpupTccdAAACKNwBACDAdfKrU+EUrceR" \
    "ieNjY1l6tTbat/b59ezAGHTcAQAggMIdAAAC2FWmgMRIQzXpO8z4KX62SFzzI5t7xtf+YqaRWfPH8G2qR8cdAAACKNwBACCAqMxJ" \
    "jPloIXFdGb/CK8/CY4nvt56IzdSg4w4AAAEU7gAAEEBUhu7YYaa+Xs8LAFrScQcAgAAKdwAACCAqc6DE2Ea69NjMEr2eF4D3W00j" \
    "RDqr0nEHAIAACncAAAggKtOYMR9bzI0jE9eVceq+rAF6lbi2RyY2cywddwAACKBwBwCAAKIyDCM9apJ4zADAfnTcAQAgwMVPEQAA" \
    "QH2iMg2INMArOwxgDbCE72Yf7DDTnqgMAAAEULgDAECA62SQsQtjvizpO8xUZjzKLaNzGJNnvw0ddwAACKBwBwCAAHaVYXhiM3AM" \
    "o3Nued/CejruAAAQQOEOAAABRGU2MOaDV2IPrCU2MybfzTF53vej4w4AAAEU7gAAEEBUBm7YYWY5485z9bRWlxy/9Qag4w4AABEU" \
    "7gAAEEBUZqX0kTRAorl3rwhNfb6b3LLDzDY67gAAEEDhDgAAAa7TZErxFmO+MfW0a8dejDWpRoSmJu9MlhCbWU/HHQAAAijcAQAg" \
    "gF1lwolzHMN1pjLr854IDdAjHXcAAAigcAcAgACiMjOMm+GVaAE9sYtFO76bbOHZXEbHHQAAAijcAQAggKjMjZQxnxHSuUbYwcMa" \
    "yzXC+tyLnWe2s8ZoQWxmno47AAAEULgDAEAAUZlwxpTAHLGZ5xjTA1VdvJEAAKA+URkAAAgwfFQmZXxsXEtr1ljfxGaeIzZzz/rh" \
    "SJ7B/9NxBwCAAAp3AAAIMGRUJmXMZyRUU8r6gTliM88xsgfOdpm8egAAoDxRGQAACDBkVAbWGiFOIAYwprl7PcKaZznrgQp8p3Tc" \
    "AQAggsIdAAACDBOVSRnzjTr6oRbjSERoHhvhGXGvqWyEZ/BTdNwBACCAwh0AAAIME5WpbKQRTxJjYrgnQgPH+P7Hd/89az//9MHz" \
    "xTRNOu4AABBB4Q4AAAG6jsoY3cJ2o/7kPuuMHKHp6Rl5efnf4UefS0/EZh7r6Rl8i447AAAEULgDAECA7qIyKWPZ3kc5qVLWD6QY" \
    "OUKTSAzjXLeRmCX/jft1r/fYjI47AAAEULgDAECA7qIysJaR/XK9jyA5jghNHa55HbfRlyWxGcaj4w4AAAEU7gAAEODaw+9XSBnz" \
    "iRbQE7EZWrhdSynv9kSubR/sMPNYj98pHXcAAAigcAcAgACxu8okjvkSj7lX7gXUJzbDyOwws69eYjM67gAAEEDhDgAAAWKjMkAd" \
    "vYwgoWfiRn2zw8wYLr6wAABQn6gMAAAEiIrKGPOxhfVzDLEZWrDDzHNcqz7YYWZfyd8pHXcAAAigcAcAgADlozLGfGyRuH5EAuCe" \
    "ZwGWs8NMv3TcAQAgwGWKiuQDAMCYykdlYGTpsZnkn9yHVInvCpazw8y+0r5TojIAABBA4Q4AAAFKRmWM+dgicf0kjOfgaInP8llc" \
    "K+bYYWa5hNiMjjsAAARQuAMAQICSURngnh1mmJO4HoDt7DAzHh13AAAIoHAHAIAAZaIyRr1skbh+tsRFxGagjrPWcOKzz7nsMLNc" \
    "1e+UjjsAAARQuAMAQIBTozLGfGxh/QCj8d5jjh1m2qkUm9FxBwCAAAp3AAAIUGZXGRhBixGbHWbgeNYq6ewwk0nHHQAAAijcAQAg" \
    "wOFRmcRRPnUkrh8j9eXEZuBe4nuPc9lhpp2zv1M67gAAEEDhDgAAAQ6JyiSO+VLG9InXlnbSd5iBylK+C7CWHWaec0ZsRscdAAAC" \
    "KNwBACDA9WUy+aO2xMhHhZF6emzm7J/ch2k6b+0lPrPUZIeZvui4AwBAAIU7AAAEaLarTOKYzzi+jsT1A/RBPIaR2WHmOUfFO3Xc" \
    "AQAggMIdAAAC7BqVSRzzicewl8pryQ4z8Jh1xQjsMJNPxx0AAAIo3AEAIMDV71+iisQIB8cTm2EvFdaP9x6V2WHmOS2/UzruAAAQ" \
    "QOEOAAABNu8qkzjmqzAepQ+Jayl9hxlYq9pz6rmjAjvMHGPv2IyOOwAABFC4AwBAgF1/AROslTgyrjZ23yI9NmOHGdx32E5sJoeO" \
    "OwAABFC4AwBAgJdf//j747dffW4sAgAAhem4AwBAAIU7AAAEULgDAEAAhTsAAARQuAMAQACFOwAABFC4AwBAAIU7AAAEULgDAEAA" \
    "hTsAAARQuAMAQACFOwAABFC4AwBAAIU7AAAEuLycfQQAAMCbdNwBACCAwh0AAAIo3AEAIIDCHQAAAijcAQAgwGWa7CsDAADV6bgD" \
    "AEAAhTsAAARQuAMAQICLiDsAANSn4w4AAAGuR/+DH97/8vHZP/vuh+8i5gPp57j2+Lcc85J/68hrUu3c9/q3lmh9Lyrc69bXPPGe" \
    "3qrw/rnlXdrOlmu7lxbnW+E9s0Ti2vb+XK7lsem4AwBAAIU7AAAEaBaVaTGGm/s7U8ZGW/7OCqO9ObfHvOQ4K4xo9zLyuS+Rfr5r" \
    "7y/Paf0uTbl3icfMYyPXCYnrea/71fIe6bgDAEAAhTsAAATYNSqTPhZf4qxzTBw53RptbdzeoxHOfQTpz2A1ngt6pU64l3JsCXTc" \
    "AQAggMIdAAACbI7KHLlBfYXx01qj7TRSeRwGe7HOn+N78dzf02KNtbieIz8L6oRxnP0u0nEHAIAACncAAAjQ7BcwzdkySksZw609" \
    "zl53IOnpXNYa+dxhLyN8LxhT6zqhcpyv8rEtsTY2tvc56rgDAEAAhTsAAAQ4PCrTqyPHPeljJuiJWNS+Et9pa9dAT7EH2KLC+7NF" \
    "XLnlM6vjDgAAARTuAAAQQFRmJyOPMteOmXraRWfkcx+B+wXwnMT3Z0JsRscdAAACXIZqDQMAQKjYqExP0ZQtOxKkSDzmteZGbD2d" \
    "e6/ntUTi2DfRXmts7h7ttW63rIG9/uxoz+DI0t85ld+fW94VZ5yLqAwAAARQuAMAQIDNUZktv0gixQjnuBej21cjXAfr/NXI16E1" \
    "15YU1eqEEb5BrbWO2z1Lxx0AAAIo3AEAIEDsrjKjOXs0Q//Oin9Y2+MYLWLUYlecuf/Gc1SHd+lj6e+Bs49Zxx0AAAIo3AEAIMCu" \
    "UZm5MU2LscJZI6HW55gy6qJvrUeZPa3z9LHvWRK/F+4va3mXPlbh/Zl2jy5T9C0HAIAxiMoAAECAl9/+/OfjN19+pu8OAACF6bgD" \
    "AEAAhTsAAARQuAMAQACFOwAABFC4AwBAAIU7AAAEULgDAEAAhTsAAAT4F2fUNxY2f1iDAAAAAElFTkSuQmCC" \
    ""

#endif // AXIS_LOGO_H
